### ISSUE TITLE
Gracefully exit if render fails

### ISSUE THREAD

**Issue by jonocarroll** [yonicd/covrpage#1]
If not all dependencies of a package are installed (e.g. the package hasn't been built/installed yet) then `rmarkdown::render` fails. Perhaps wrap in a `try`-like context or confirm that the package being checked is itself installed.

**Comment by yonicd** [comment]
this should fix it https://github.com/yonicd/covrpage/commit/3641f4b049adfe7415f04fd0c4a22c37f5ef6aac
