### ISSUE TITLE
pkgdown gives warning while building "tests_and_coverage" vignette

### ISSUE THREAD

**Issue by IndrajeetPatil** [yonicd/covrpage#19]
I am creating the vignette `tests_and_coverage.Rmd` using `covrpage::use_covrpage_vignette()`. After this, when I build the vignette for the package website using `pkgdown::build_article("tests_and_coverage")`, I get the following warning:
```
Warning in if (!is.na(existing)) { :
  the condition has length > 1 and only the first element will be used
```
The vignette html is rendered properly by `pkgdown`, so not sure why the `warning`.

**Comment by yonicd** [comment]
yes i saw that too. not sure where that comes from, but have ignored it since it didnt effect the site that is built.

**Comment by yonicd** [comment]
i think [this](https://github.com/r-lib/pkgdown/blob/77ceb8cc8bc815020a24f1f690e91d590d3a52e2/R/html-tweak.R#L79) is the gensis of the warning

**Comment by yonicd** [comment]
This is labeled as a bug in pkgdown. Closing here. Look at above reference for bug resolution.
