### ISSUE TITLE
rendering `README.md` document even when the tests fail

### ISSUE THREAD

**Issue by IndrajeetPatil** [yonicd/covrpage#20]
If I am not mistaken, currently if any of the test fails, the existing `README.md` document is not  updated, right?

I am wondering if it will be possible for `covrpage::covrpage()` to generate this document even when tests fail and add the count of failed tests in the `failed` column of the respective table.

For example, two of my tests fail for function `lm_effsize_ci`:
```
Quitting from lines 57-62 (_covrpage.Rmd) 
Error: Failure in `C:/Users/inp099/AppData/Local/Temp/RtmpGwN3eM/R_LIBS2c5862e6c43/ggstatsplot/ggstatsplot-tests/testthat.Rout.fail`
h grouping and labeling, which is not allowed.-- 1. Failure: lm_effsize_ci works (@test_lm_effsize_ci.R#59)  ----------------------------------------------------------------
df2$conf.low[2] not equal to 0.09086971.
1/1 mismatches
[1] 0.0762 - 0.0909 == -0.0147

-- 2. Failure: lm_effsize_ci works (@test_lm_effsize_ci.R#60)  ----------------------------------------------------------------
df2$conf.high[2] not equal to 0.3558572.
1/1 mismatches
[1] 0.39 - 0.356 == 0.0339

== testthat results  ==========================================================================================================
OK: 52 SKIPPED: 1 FAILED: 2
1. Failure: lm_effsize_ci works (@test_lm_effsize_ci.R#59) 
2. Failure: lm_effsize_ci works (@test_lm_effsize_ci.R#60) 

Error: testthat unit tests failed
Execution halted
```

But since the doucment is not updated, the table still reads like the following:

![image](https://user-images.githubusercontent.com/11330453/46497219-f6fdc880-c7e7-11e8-86cc-af780d6165a5.png)

**Comment by yonicd** [comment]
It should have fails in the table and skip them for covr. What version of covrpage are you using?

**Comment by yonicd** [comment]
you can see this issue https://github.com/yonicd/covrpage/issues/11 where this was worked out

**Comment by yonicd** [comment]
in the chunk that failed you put in all the expectations in the same chunk 

https://github.com/IndrajeetPatil/ggstatsplot/blob/0382ae567a2d1c466286b98c071b14a3afc1fa82/tests/testthat/test_lm_effsize_ci.R#L50_L63

which is fine, but it would make it easier to maintain the tests and readability if you use describe/it convention for tests that are bundled. 

this is an example:

https://github.com/yonicd/carbonate/blob/master/tests/testthat/test-uri.R#L13_L23

where the corresponding output in the report you can see here with the `a:b` description convention

https://github.com/yonicd/carbonate/tree/master/tests

It will also make the report easier to read. 

in any case I cant really split up the 2 from the 9 tests in the chunk from the report.

**Comment by yonicd** [comment]
there was a bug in the test_summary function. I thought it was giving flags yes/no for non-passing expectations, and in practice it is returning the count of non pass expectations by type in each test file.

here is the patch commit

https://github.com/yonicd/covrpage/commit/8cb6c6dce37cbfcd122fc7663b2f79245a111724

here is the output in the fork i made.

https://github.com/yonicd/ggstatsplot/tree/master/tests

notice in the testthat summary it indicated 2 tests failed out of 9 

and in the testthat details it shows the chunk where they failed.
