### ISSUE TITLE
problems displaying icons properly on a windows machine

### ISSUE THREAD

**Issue by IndrajeetPatil** [yonicd/covrpage#22]
Pretty sure this is an issue about the Unicode handling in R (under windows). This is what the `README` page looks like:
https://github.com/IndrajeetPatil/ggstatsplot/tree/master/tests

1.
![image](https://user-images.githubusercontent.com/11330453/46672007-5a02ad00-cba4-11e8-8f7d-1aeee03d2b63.png)

2.
![image](https://user-images.githubusercontent.com/11330453/46672043-6dae1380-cba4-11e8-8cc0-0a0e4867a86f.png)

3.
![image](https://user-images.githubusercontent.com/11330453/46672089-8ae2e200-cba4-11e8-93ca-887bc5e151ad.png)

**Comment by yonicd** [comment]
nice! i'll try to figure something out.

**Comment by yonicd** [comment]
digging into this a bit it looks like rmarkdown isnt rendering the unicode. the unicode is being read in right. 

this is the [warning icon](https://www.google.com/search?q=%3CU%2B26A0%3E%3CU%2BFE0F%3E&oq=%3CU%2B26A0%3E%3CU%2BFE0F%3E&aqs=chrome..69i57j33.349j0j7&sourceid=chrome&ie=UTF-8) in windows

**Comment by IndrajeetPatil** [comment]
Sorry, couldn't get back to you on Twitter about this. Busy day.

Yeah, this looks good as a temporary solution!

**Comment by yonicd** [comment]
For a endlessly long discussion on the issue (sink()). See [here](https://github.com/r-lib/evaluate/issues/59)
