### ISSUE TITLE
details in vignette, Firefox

### ISSUE THREAD

**Issue by maelle** [yonicd/covrpage#25]
I haven't worked out yet whether it's a problem in `covrpage`/`pkgdown`/`pandoc` so recording this here. 👼 

In https://yonicd.github.io/covrpage/articles/tests_and_coverage.html on Firefox "Session Info" is clickable but looks like this i.e. without the arrow on the left.

![image](https://user-images.githubusercontent.com/8360597/48352859-3264a000-e68e-11e8-9c5b-021b7b601711.png)

**Comment by maelle** [comment]
cf https://github.com/r-lib/pkgdown/issues/884

**Comment by yonicd** [comment]
in my firefox i dont see the triangles, but i can click on the `<summary>` text and it opens up the content.

**Comment by maelle** [comment]
Yes same here, it is just unintuitive, but not a bug from this package
