### ISSUE TITLE
create dummy package examples for failed and skipped tests

### ISSUE THREAD

**Issue by yonicd** [yonicd/covrpage#26]
have dummy packages that can be used in examples and vignettes to show how the outputs to such outcomes should be used and interpreted.

**Comment by maelle** [comment]
* One for each?

* Under which GitHub account?

* What would be an example of a good reason to skip a test, with the user still trusting the package? Interactive stuff?

* Did you use any such dummy package whilst testing `covrpage`?

**Comment by yonicd** [comment]
there is a dummy benchmark package in the [tests/assets/benchmark](https://github.com/yonicd/covrpage/tree/master/tests/assets) folder.

[remedy](https://github.com/ThinkR-open/remedy) is a good example for skipping tests, even covrpage is a good example for skipping tests (nearly all cant be run on travis)

there are cases when developers skip problem tests on purpose just to get it to run on the non-problematic ones.

I actually asked this [very question](https://twitter.com/yoniceedee/status/1060767090867605504) of the validity of a package on twitter and only @colinfay responded.

**Comment by maelle** [comment]
I don't see skipped tests in https://github.com/ThinkR-open/remedy/tree/master/tests#tests-and-coverage, what URL should I use in the vignette? I'm thinking using the examples you mention will be more doable than my creating packages.

Yeah Twitter is not always the best place for questions. :wink:

**Comment by maelle** [comment]
I can't open the submodule in https://github.com/yonicd/covrpage/tree/master/tests/assets, so for that, what URL should be used for the vignette?

**Comment by yonicd** [comment]
Not sure why it is locking that directory

**Comment by yonicd** [comment]
I’ll open a few repos that we can use covrpage_example_skip covrpage_example_fail

**Comment by yonicd** [comment]
[covrpage_example_fail](https://github.com/yonicd/covrpage_example_fail)
[covrpage_example_skip](https://github.com/yonicd/covrpage_example_skip)
