### ISSUE TITLE
new vignettes for different potential users

### ISSUE THREAD

**Issue by yonicd** [yonicd/covrpage#27]
create new vignettes that explain how end users and other developers can benefit from using the package.

**Comment by yonicd** [comment]
for developers a deeper explanation of how to use the package failing output, and when it is relevant.

**Comment by maelle** [comment]
For users, "This package extends the information that is communicated with the potential user with a cover page for the tests in the form of summary tables of results from covr and testthat." make the potential user understand how to use the information.

_I_ am not sure how to use it: would you tell users to stay away from a version with failing tests for instance? 

There's also an aspect `covrpage` can't simplify, I think: you might have a failing test, and a corresponding issue in the issue tracker. In the `covrpage` report, one would only see the failing test, no link to that existing issue.

**Comment by maelle** [comment]
could this issue be closed in favor of two distinct issues, one per vignette?

**Comment by yonicd** [comment]
closing in favor of the other issues for each user type
