### ISSUE TITLE
group references in pkgdown site

### ISSUE THREAD

**Issue by yonicd** [yonicd/covrpage#29]
grouping of functions in the references for pkgdown

Function|Description|Group
-- | --|--
coverage_skip() | Run covr with failing tests|Testing Utility
covr_log() | Log of code coverage| Postprocess
covr_summary() | Summary outputs for covr object|Output Manipulation
covrpage() | Render covrpage|Invoking
covrpage_ci() | covrpage for travis|Invoking
covrpage_log() | Log of covrpage outputs|Postprocess
make_badge() | Create covrpage Badge| Setup
map_test() | Map a single test file| Testing Utility
map_testthat() | Hierarchy structure of testthat tests|Testing Utility
%>% | Re-export magrittr pipe operators|General Utility
sinfo() | importFrom utils sessionInfo packageVersion|General Utility
tencrypt() | Encrypt Travis environment variables|Setup
testthat_summary() | Summary outputs for testthat object|Output Manipulation
use_covrpage() | Add covrpage to Travis CI for a git directory|Setup
use_covrpage_vignette() | Create a vignette for covrpage|Setup

**Comment by maelle** [comment]
Should this be closed?

Any interest in my re-creating the grouping using concepts with `roxygen2` so that the functions might be "grouped" in the local docs as well?

**Comment by yonicd** [comment]
concepts added https://github.com/yonicd/covrpage/commit/d7bd8b54c3b5ffbf7097f9ff9060319d5af14231
