### ISSUE TITLE
Explore Appveyor deploy?

### ISSUE THREAD

**Issue by maelle** [yonicd/covrpage#31]

**Comment by yonicd** [comment]
this is a technical thing. in practice a release/tag need to be made for appveyor to deploy. i couldnt understand how to make this work with git/tic/appveyor. I'm sure someone more adept with that workflow can do it easily.

**Comment by maelle** [comment]
I don't know anyone adept with that workflow, sorry.

**Comment by yonicd** [comment]
Let’s just leave it then.
