### ISSUE TITLE
Create a vignette for package developers

### ISSUE THREAD

**Issue by maelle** [yonicd/covrpage#32]
"Get started"

for developers a deeper explanation of how to use the package failing output, and when it is relevant.

@yonicd do you have examples of cases in your own packages where the report informed development?

cf #27

**Comment by maelle** [comment]
The vignette should explain what problem `covrpage` is trying to solve. In my own words: A coverage badge is only a number. When clicking to read the coverage report one gets as much information as one would like, but in an external website and in a nested way, whereas `covrpage` report has all the information in a single page.

I have to say that if I had to review a package, I might still look at codecov report, especially because of the report for individual R files e.g. https://codecov.io/gh/yonicd/covrpage/src/master/R/badge.R How would you answer that in a vignette @yonicd?

**Comment by yonicd** [comment]
covrpage doesnt take the place of codecov, it has higher level coverage information that can be conveyed to users before they choose to go to another site from the originating gh repo.

covrpage can give you a more targeted search in codecov. maybe a good solution is to try to build the links, in addition to the files in gh, to the codecov (when it is there) of the build. 

the only problem there is in that is like the link you gave for badge.R, the test I run locally is not always the same as in the ci's when using `skip_on_travis`. many times you `skip_on_travis` for some technical reasons that couldnt be resolved on the ci ami.

in general i would give motivation for developers the way @llrs or @IndrajeetPatil found ways to leverage the package in their development. I know that @colinfay also has some opinions on how developers can use it in their workflows.

maybe @sellorm @devinpastoor have some points to add as an onprem maintainers and how it fits in that workflow.

**Comment by yonicd** [comment]
here is a good example of a [live repo](https://github.com/llrs/GSEAdv/blob/19cbab3cff04c5c65bcef18c493a2cc650f441c2/tests/README.md) with test resulting in errors. the status badge on the root readme shows failing, jumping to tests/readme gives a quick human readable specific reason for failure.

**Comment by llrs** [comment]
@yonicd About that specific report, I'll probably open a new issue. The test are passing in my local machine using `devtools::test` (and in travis +covr), but when building the report they fail... anyway my point is that the report helps to track development.

**Comment by yonicd** [comment]
`devtools::test` runs `testthat::test_dir` `covrpage` runs `testtthat::test_check` which is akin to running tests on `covr` or cranlike environment.

**Comment by yonicd** [comment]
merged PRs https://github.com/yonicd/covrpage/commit/c76d9efa256ec6ca7b3154427784267c01689de8, https://github.com/yonicd/covrpage/commit/21299da6f28a4cd9b84716b3467c3c929e3b7b21

**Comment by llrs** [comment]
There's a comment: "" that I think should link to the other vignette.

**Comment by yonicd** [comment]
Yes. Thanks for pointing that comment out. It was on a todo for later today.
