### ISSUE TITLE
use tic for deploying the website of this package?

### ISSUE THREAD

**Issue by maelle** [yonicd/covrpage#34]
If you run `travis::use_tic()` the setup would then be to have the pkgdown website built on Travis and deployed to a gh-pages branch.

It'd probably mess up with the current Travis covrpage report setup, but worth exploring for  #28 maybe.

**Comment by maelle** [comment]
What's the status on this @yonicd, do you want to close the issue? If I remember correctly you tried that setup in a branch.

**Comment by yonicd** [comment]
closing issue. successful deployment in [tic branch](https://github.com/yonicd/covrpage/commit/d6a576bf40aec1c546fc1001128d3c4415774ac0)
