### ISSUE TITLE
typo in "tests_and_coverage" vignette

### ISSUE THREAD

**Issue by IndrajeetPatil** [yonicd/covrpage#35]
The vignette produced by `covrpage` has a typo: 
"contigency" should be  "contingency"

**Comment by yonicd** [comment]
I can't find that word in the vignette, can you link to it?

**Comment by IndrajeetPatil** [comment]
My bad! I found it with `devtools::spell_check()` in the "Test and Coverage" vignette so assumed it must be coming from `covrpage`, but the spelling error is on my part.

Sorry for the false alarm.
