### ISSUE TITLE
`skip_on_cran()` reduces code coverage

### ISSUE THREAD

**Issue by IndrajeetPatil** [yonicd/covrpage#52]
Recently I submitted my package and got this comment from `CRAN` maintainers and so I had to add `skip_on_travis()` for a lot of tests to reduce the duration of running tests on `CRAN` machines. 
```
Can't you rather provide a reduced test set of most important tests and 
run less important ones only conditionally if some env var is set that 
you only define on your machine?
```

But when I re-ran `covrpage::covrpage()`, my code coverage dropped from `95%` to `80%`. Is there any way for `covrpage` to also include skipped tests while computing code coverage?

**Comment by yonicd** [comment]
they werent actually run. 

covrpage runs test_check which is what covr runs. 

it better reflects what is being tested. 

you are correct when using skip_on_travis, that will run the test in covrpage.

When submitting to CRAN I add for them the skip_on_cran where relevant.

This does create a divergence in coverage in the package cran documentation and the GH/pkgdown coverage, but i think this is ok since the report reflects in each case the system that it was created on.

**Comment by IndrajeetPatil** [comment]
> covrpage runs test_check which is what covr runs.

Interesting. Although I am skipping tests on `CRAN`, my code coverage on both `codecov` and `coveralls` has remained unchanged-
https://codecov.io/gh/IndrajeetPatil/ggstatsplot?branch=master
https://coveralls.io/github/IndrajeetPatil/ggstatsplot?branch=master

And both of these services, if I am not mistaken, rely on `covr`. For example, my `.travis.yml` looks something like this-
```yaml
after_success:
  - Rscript -e 'covr::codecov()'
  - Rscript -e 'covr::coveralls(type = "all")'
```

That's why I was a bit confused as to why `covrpage` code coverage dropped.

**Comment by IndrajeetPatil** [comment]
You are right! The local `covr` addin shows the same code coverage as `covrpage`.

![image](https://user-images.githubusercontent.com/11330453/49663658-5745fc00-fa1d-11e8-9156-739d81d44254.png)

I wonder what's different about how `codecov` and `coveralls` are computing it. Anyway, if `covrpage` relies on `covr` in the backdrop then I guess nothing can be done about this. 

I'll leave it to you to decide if you want to close this issue.

**Comment by yonicd** [comment]
i'll leave as is. the report reflects the system it was run on. thanks for checking that.
