### ISSUE TITLE
Return working dir to original working dir in on.exit block

### ISSUE THREAD

**Issue by drexell0680** [yonicd/covrpage#7]
I see the `setwd` in the [`on.exit` ](https://github.com/yonicd/covrpage/blob/master/R/covrpage.R#L81), but it's not returning to the working directory on error for some reason.  In particular, when building my `root/README.md` fails.

**Comment by yonicd** [comment]
on.exit doesnt trigger on a failed build?

**Comment by yonicd** [comment]
i was trying to take failed tests into account in a [branch](https://github.com/yonicd/covrpage/tree/master#todo), to try and avoid failed tests. it is also connected to this [issue](https://github.com/yonicd/covrpage/issues/3)

**Comment by yonicd** [comment]
connecting with issue [3](https://github.com/yonicd/covrpage/issues/3)
